### ISSUE TITLE
can't compile with vs2019

### ISSUE THREAD

**Issue by JonasSamuelsson** [danielpalme/IocPerformance#111]
I just tried to comile with vs2019 and got the following error
```
Fody: PEVerify of the assembly failed.
[IL]: Error: [C:\dev\GitHub\IocPerformance\IocPerformance\bin\Debug\IocPerformance.exe : DryIocZero.Request::ToString][offset 0x0000002B] Cannot change initonly field outside its .ctor.(Error: 0x80131884)
```
seems to be related to your code @dadhi, can you have a look?

**Comment by danielpalme** [comment]
I had the same problem yesterday.
Cleaning the _bin_ and _obj_ directories and restarting VS2019 did the trick.

See #106.

**Comment by JonasSamuelsson** [comment]
I've tried that, on two different machines, but still can't compile

**Comment by danielpalme** [comment]
Sometimes it helps to Build -> Rebuild -> Build.
The problem is caused by https://github.com/dadhi/DryIoc which uses Fody

**Comment by AArnott** [comment]
When I checkout master from this repo, it won't build:

```
1>    Fody:   Verifying assembly
1>MSBUILD : error : Fody: PEVerify of the assembly failed.
1>MSBUILD : error : [IL]: Error: [C:\Users\andarno\Source\Repos\IocPerformance\IocPerformance\bin\Debug\IocPerformance.exe : DryIocZero.Request::ToString][offset 0x0000002B] Cannot change initonly field outside its .ctor.(Error: 0x80131884)
1>MSBUILD : error : 1 Error(s) Verifying C:\Users\andarno\Source\Repos\IocPerformance\IocPerformance\bin\Debug\IocPerformance.exe
1>    Fody:   Finished verification in 3244ms.
```

Also, compile is *danged slow*. If this is all fody's fault, I think that should be called out when reporting metrics on various containers (e.g. " ❗️ this uses fody, and dramatically slows down your build")

The workaround to "build, rebuild, build" is no workaround. It's just that fody's buggy code gen and verification step don't run after an otherwise successful build, so the verification is skipped. Every time I meet a project that uses fody, I run screaming asap.

**Comment by Barsonax** [comment]
Might actually be better to remove it completely in my opinion. It takes ages to build.

**Comment by danielpalme** [comment]
I just removed DryIocZero and Cauldron (both are using Fody).
Build should now work faster and reliably.
